name: Configure XStore

on:
  workflow_dispatch:

jobs:
  configure-xstore:
    runs-on: [self-hosted, vm1]
    steps:
    - name: Check for AppData directory
      id: check-appdata
      shell: powershell
      run: |
        $appDataPath = "$env:APPDATA\Roaming\Sherwin-Williams-POS"
        if (Test-Path $appDataPath) {
          Write-Output "::notice::AppData directory exists at $appDataPath"
          Write-Output "::set-output name=appdata_exists::true"
        } else {
          Write-Output "::set-output name=appdata_exists::false"
        }

    - name: Launch XStore to create AppData directory
      if: steps.check-appdata.outputs.appdata_exists == 'false'
      shell: powershell
      run: |
        $xstorePath = "C:\Program Files (x86)\Sherwin-Williams-POS\Sherwin-Williams-POS.exe"
        Write-Output "Launching XStore to create AppData directory..."
        
        # Start process and wait briefly
        $process = Start-Process -FilePath $xstorePath -PassThru
        Start-Sleep -Seconds 10
        Stop-Process -Id $process.Id -Force
        
        # Verify directory was created
        $appDataPath = "$env:APPDATA\Roaming\Sherwin-Williams-POS"
        if (-not (Test-Path $appDataPath)) {
          Write-Output "::error::Failed to create AppData directory"
          exit 1
        }
