name: Configure XStore

on:
  workflow_dispatch:

jobs:
  configure-xstore:
    runs-on: [self-hosted, vm1]
    steps:
    - name: Check for AppData directory
      id: check-appdata
      shell: powershell
      run: |
        $appDataPath = "$env:APPDATA\Sherwin-Williams-POS"
        Write-Output "Checking for directory: $appDataPath"
        
        if (Test-Path $appDataPath) {
          Write-Output "Directory exists at $appDataPath"
          Write-Output "appdata_exists=true" >> $env:GITHUB_OUTPUT
          
          # List directory contents for debugging
          Write-Output "Directory contents:"
          Get-ChildItem $appDataPath | Format-Table -AutoSize | Out-String -Width 200 | Write-Output
        } else {
          Write-Output "Directory does not exist"
          Write-Output "appdata_exists=false" >> $env:GITHUB_OUTPUT
        }

    #- name: Launch XStore to create AppData directory
      #if: steps.check-appdata.outputs.appdata_exists == 'false'
      #shell: powershell
      #run: |
      #  $xstorePath = "C:\Program Files (x86)\Sherwin-Williams-POS\Sherwin-Williams-POS.exe"
      #  Write-Output "Launching XStore to create AppData directory..."
        
        # Start process and wait briefly
      #  $process = Start-Process -FilePath $xstorePath -PassThru
      #  Start-Sleep -Seconds 10
      #  Stop-Process -Id $process.Id -Force
        
        # Verify directory was created
      #  $appDataPath = "$env:APPDATA\Roaming\Sherwin-Williams-POS"
      #  if (-not (Test-Path $appDataPath)) {
      #    Write-Output "::error::Failed to create AppData directory"
      #    exit 1
      #  }
