name: Package & Deploy

on:
  workflow_dispatch:
    inputs:
      target_cluster:
        type: choice
        required: true
        description: Target Cluster Name (dev-xstore, qa-xstore, lab-xstore, etc.)
        options:
          - dev-xstore
          - qa-xstore
          - lab-xstore
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print target cluster
        run: echo "Target cluster:${{ inputs.target_cluster }}"

      - name: Log the inputs
        run:  |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          
      - name: Running Healthchecks
        run: |
          echo "Validating Solarsystem healthcheck"
          if ! curl -sf http://192.168.68.115:30344; then
            echo "Application endpoint is unavailable!" && exit 1
          fi

