name: Package & Deploy

on:
  workflow_dispatch:
    inputs:
      target_cluster:
        type: choice
        required: true
        description: Target Cluster Name (dev-xstore, qa-xstore, lab-xstore, etc.)
        options:
          - dev-xstore
          - qa-xstore
          - lab-xstore
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      store_number:
        description: 'Store number, e.g. lb9970'
        required: true
        type: string 

jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print target cluster
        run: echo "Target cluster:${{ inputs.target_cluster }}"

      - name: Log the inputs
        run:  |
          echo "Tags: $TARGET"
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Tags: $STORE"
        env:
          TARGET: ${{ inputs.target_cluster }}
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          STORE: ${{ inputs.store_number }}

      - name: Application Endpoint Check
        run: |
          if curl -sf https://www.google.com; then
            echo "Application endpoint is available!"
          else
            echo "Application endpoint is unavailable!"
            exit 1
          fi
