name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-install:
    runs-on: [self-hosted, vm1]  # Matches your custom labels
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check if XStore exists
        shell: powershell
        run: |
          $installPath = "C:\Program Files\XStore\XStore.exe"
          if (Test-Path $installPath) {
            Write-Output "XStore already installed at $installPath"
          } else {
            Write-Output "XStore not installed! Running installation script"
            try {
              .\scripts\install-xstore.ps1 -ErrorAction Stop
              Write-Output "Installation completed successfully"
            } catch {
              Write-Error "Installation failed: $_"
              exit 1
            }
          }
